/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/theme.source.ts
 * Command: astryx theme build src/themes/theme.source.ts
 * Generated: 2026-10-07T14:00:52.700Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
