/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/theme.source.ts
 * Command: astryx theme build src/themes/theme.source.ts
 * Generated: 2026-10-07T14:00:52.701Z
 */

/// <reference path="./scheduler.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const schedulerTheme: DefinedTheme;
