/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as ProjectProjectSlugRouteImport } from './routes/project/$projectSlug'
import { Route as ProjectVoteRouteImport } from './routes/project/vote'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectProjectSlugVoteRouteImport } from './routes/project/$projectSlug_.vote'
import { Route as ApiVotesIdStreamRouteImport } from './routes/api/votes.$id.stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectSlugRoute = ProjectProjectSlugRouteImport.update({
  id: '/project/$projectSlug',
  path: '/project/$projectSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectVoteRoute = ProjectVoteRouteImport.update({
  id: '/project/vote',
  path: '/project/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectSlugVoteRoute = ProjectProjectSlugVoteRouteImport.update({
  id: '/project/$projectSlug_/vote',
  path: '/project/$projectSlug/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVotesIdStreamRoute = ApiVotesIdStreamRouteImport.update({
  id: '/api/votes/$id/stream',
  path: '/api/votes/$id/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRoute
  '/project/vote': typeof ProjectVoteRoute
  '/project/': typeof ProjectIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectSlug/vote': typeof ProjectProjectSlugVoteRoute
  '/api/votes/$id/stream': typeof ApiVotesIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRoute
  '/project/vote': typeof ProjectVoteRoute
  '/project': typeof ProjectIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectSlug/vote': typeof ProjectProjectSlugVoteRoute
  '/api/votes/$id/stream': typeof ApiVotesIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$projectSlug': typeof ProjectProjectSlugRoute
  '/project/vote': typeof ProjectVoteRoute
  '/project/': typeof ProjectIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/project/$projectSlug_/vote': typeof ProjectProjectSlugVoteRoute
  '/api/votes/$id/stream': typeof ApiVotesIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project/$projectSlug'
    | '/project/vote'
    | '/project/'
    | '/api/auth/$'
    | '/project/$projectSlug/vote'
    | '/api/votes/$id/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/project/$projectSlug'
    | '/project/vote'
    | '/project'
    | '/api/auth/$'
    | '/project/$projectSlug/vote'
    | '/api/votes/$id/stream'
  id:
    | '__root__'
    | '/'
    | '/project/$projectSlug'
    | '/project/vote'
    | '/project/'
    | '/api/auth/$'
    | '/project/$projectSlug_/vote'
    | '/api/votes/$id/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectProjectSlugRoute: typeof ProjectProjectSlugRoute
  ProjectVoteRoute: typeof ProjectVoteRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProjectProjectSlugVoteRoute: typeof ProjectProjectSlugVoteRoute
  ApiVotesIdStreamRoute: typeof ApiVotesIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug': {
      id: '/project/$projectSlug'
      path: '/project/$projectSlug'
      fullPath: '/project/$projectSlug'
      preLoaderRoute: typeof ProjectProjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/vote': {
      id: '/project/vote'
      path: '/project/vote'
      fullPath: '/project/vote'
      preLoaderRoute: typeof ProjectVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectSlug_/vote': {
      id: '/project/$projectSlug_/vote'
      path: '/project/$projectSlug/vote'
      fullPath: '/project/$projectSlug/vote'
      preLoaderRoute: typeof ProjectProjectSlugVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/votes/$id/stream': {
      id: '/api/votes/$id/stream'
      path: '/api/votes/$id/stream'
      fullPath: '/api/votes/$id/stream'
      preLoaderRoute: typeof ApiVotesIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectProjectSlugRoute: ProjectProjectSlugRoute,
  ProjectVoteRoute: ProjectVoteRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProjectProjectSlugVoteRoute: ProjectProjectSlugVoteRoute,
  ApiVotesIdStreamRoute: ApiVotesIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
