/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme.source.ts
 * Command: astryx theme build src/theme.source.ts --out src/theme.css
 * Generated: 2026-07-21T11:12:24.576Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
