/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme.source.ts
 * Command: astryx theme build src/theme.source.ts --out src/theme.css
 * Generated: 2026-07-21T11:12:24.577Z
 */

/// <reference path="./scheduler.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const schedulerTheme: DefinedTheme;
